[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend && python3 manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && python3 manage.py migrate && gunicorn note_translate.wsgi:application --bind 0.0.0.0:$PORT"
